/************************************************************************************************************************************************************
    Name:           EHT_Asset_Constants
    Author:         Accenture
    Description:    This Classss contains all the constants for EHT Asset classessssssssssssssssssssssss.
    Date                  PRJ/DFCT/ENHC#          Summary of Changes 
    ---------------     ------------------      ------------------------------
    5th Oct 2015        EHT Asset                Initial                                                                          
*************************************************************************************************************************************************************/
public class EHT_Asset_Constants {
    public final static String BUDGET_STATUS = 'Active';
    public final static String FUND_REQUEST_STATUS_SUBMITTED = 'Submitted';
    public final static String FUND_REQUEST_STATUS_AVAILABLE = 'Available';
    public final static String FUND_CLAIM_STATUS_APPROVED = 'Approved';
    public final static String DISPLAYSECTIONONE= 'displaysectionone';
    public final static String DISPLAYSECTIONTWO= 'displaysectiontwo';
    public final static String DISPLAYSECTIONTHREE= 'displaysectionthree';
    public final static String DISPLAYMESSEGE= 'displaymessege';
    public final static String LEADTYPE= 'Lead';
    public final static String PARTNER= 'Partner';
    public final static String SITE_REGISTRATION= 'Site Registration';
    public final static String RESOURCE= '/resource/';
    public final static String BACKWORD_SLASH= '/';
    public final static String UNDERSCORE= '__';
    public final static String IDTYPE= 'id';
}